// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/time/510.GetSynchronizationMasterInfo.0.1.uavcan
//
// Template:
// ServiceType.j2
//
// Generated at:  2020-08-21 01:54:42.711275 UTC
// Is deprecated: no
// Fixed port ID: 510
// Full name:     uavcan.time.GetSynchronizationMasterInfo
// Version:       0.1

#ifndef UAVCAN_TIME_GET_SYNCHRONIZATION_MASTER_INFO_INCLUDED
#define UAVCAN_TIME_GET_SYNCHRONIZATION_MASTER_INFO_INCLUDED

#include <nunavut/support/nunavut.h>
#include <uavcan/time/TAIInfo_0_1.h>
#include <uavcan/time/TimeSystem_0_1.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
// +------------------------------------------------------------------------------------------------------------------+
// | Begin service definitions for uavcan_time_GetSynchronizationMasterInfo_0_1
// +------------------------------------------------------------------------------------------------------------------+



typedef struct
{
    uint8_t _dummy_;
} uavcan_time_GetSynchronizationMasterInfo_0_1_Request;

/// Initialize an uavcan_time_GetSynchronizationMasterInfo_0_1_Request instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_time_GetSynchronizationMasterInfo_0_1_Request_init(uavcan_time_GetSynchronizationMasterInfo_0_1_Request* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->_dummy_ = 0U;
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_time_GetSynchronizationMasterInfo_0_1_Request
/// instance.
#define uavcan_time_GetSynchronizationMasterInfo_0_1_Request_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (0U)


// +------------------------------------------------------------------------------------------------------------------+


typedef struct
{
    float error_variance;
    uavcan_time_TimeSystem_0_1 time_system;
    uavcan_time_TAIInfo_0_1 tai_info;
} uavcan_time_GetSynchronizationMasterInfo_0_1_Response;

/// Initialize an uavcan_time_GetSynchronizationMasterInfo_0_1_Response instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_time_GetSynchronizationMasterInfo_0_1_Response_init(uavcan_time_GetSynchronizationMasterInfo_0_1_Response* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->error_variance = 0;
        uavcan_time_TimeSystem_0_1_init(&(out_instance->time_system));
        uavcan_time_TAIInfo_0_1_init(&(out_instance->tai_info));
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_time_GetSynchronizationMasterInfo_0_1_Response
/// instance.
#define uavcan_time_GetSynchronizationMasterInfo_0_1_Response_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (6U)



/// uavcan_time_GetSynchronizationMasterInfo_0_1 can only be used with the fixed port identifier defined here.
#define uavcan_time_GetSynchronizationMasterInfo_0_1_FIXED_PORT_ID (510U)

/// Serialization of uavcan_time_GetSynchronizationMasterInfo_0_1_Request instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_time_GetSynchronizationMasterInfo_0_1_Request_serialize(const uavcan_time_GetSynchronizationMasterInfo_0_1_Request* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_time_GetSynchronizationMasterInfo_0_1_Request instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_time_GetSynchronizationMasterInfo_0_1_Request_deserialize(uavcan_time_GetSynchronizationMasterInfo_0_1_Request* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    

    return offset;
}


/// Serialization of uavcan_time_GetSynchronizationMasterInfo_0_1_Response instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_time_GetSynchronizationMasterInfo_0_1_Response_serialize(const uavcan_time_GetSynchronizationMasterInfo_0_1_Response* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated float32
    
        nunavutSetF32(out_buffer, offset, in_instance->error_variance);
        offset += 32;
    // End Structure: saturated float32
    // Begin Structure: uavcan.time.TimeSystem.0.1
    rc = uavcan_time_TimeSystem_0_1_serialize(&(in_instance->time_system), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.time.TimeSystem.0.1
    // Begin Structure: uavcan.time.TAIInfo.0.1
    rc = uavcan_time_TAIInfo_0_1_serialize(&(in_instance->tai_info), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.time.TAIInfo.0.1

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_time_GetSynchronizationMasterInfo_0_1_Response instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_time_GetSynchronizationMasterInfo_0_1_Response_deserialize(uavcan_time_GetSynchronizationMasterInfo_0_1_Response* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated float32
    out_instance->error_variance = nunavutGetF32(in_buffer, buf_size_bytes, offset);
    offset += 32;
    // End Structure: saturated float32
    // Begin Structure: uavcan.time.TimeSystem.0.1
    rc = uavcan_time_TimeSystem_0_1_deserialize(&(out_instance->time_system), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.time.TimeSystem.0.1
    // Begin Structure: uavcan.time.TAIInfo.0.1
    rc = uavcan_time_TAIInfo_0_1_deserialize(&(out_instance->tai_info), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.time.TAIInfo.0.1

    return offset;
}


// +------------------------------------------------------------------------------------------------------------------+
// | End service definitions for uavcan_time_GetSynchronizationMasterInfo_0_1
// +------------------------------------------------------------------------------------------------------------------+

#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_TIME_GET_SYNCHRONIZATION_MASTER_INFO */
