// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/time/TAIInfo.0.1.uavcan
//
// Template:
// StructureType.j2
//
// Generated at:  2020-08-21 01:54:42.983015 UTC
// Is deprecated: no
// Fixed port ID: None
// Full name:     uavcan.time.TAIInfo
// Version:       0.1

#ifndef UAVCAN_TIME_TAIINFO_INCLUDED
#define UAVCAN_TIME_TAIINFO_INCLUDED

#include <nunavut/support/nunavut.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#define uavcan_time_TAIInfo_0_1_DIFFERENCE_TAI_MINUS_GPS (19)
#define uavcan_time_TAIInfo_0_1_DIFFERENCE_TAI_MINUS_UTC_UNKNOWN (0)

typedef struct
{
    uint8_t difference_tai_minus_utc;
} uavcan_time_TAIInfo_0_1;

/// Initialize an uavcan_time_TAIInfo_0_1 instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_time_TAIInfo_0_1_init(uavcan_time_TAIInfo_0_1* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->difference_tai_minus_utc = 0;
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_time_TAIInfo_0_1
/// instance.
#define uavcan_time_TAIInfo_0_1_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (1U)


/// Serialization of uavcan_time_TAIInfo_0_1 instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_time_TAIInfo_0_1_serialize(const uavcan_time_TAIInfo_0_1* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint8
    
        nunavutSetUxx(out_buffer, offset, in_instance->difference_tai_minus_utc, 8);
        offset += 8;
    // End Structure: saturated uint8

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_time_TAIInfo_0_1 instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_time_TAIInfo_0_1_deserialize(uavcan_time_TAIInfo_0_1* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint8
    out_instance->difference_tai_minus_utc = nunavutGetU8(in_buffer, buf_size_bytes, offset, 8);
    offset += 8;
    // End Structure: saturated uint8

    return offset;
}


#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_TIME_TAIINFO */
