# Configuration to check whether the DSDL definitions compile 

matrix:
    include:
        - name: "DSDL Compile Check"
          language: python
          python: 2.7
          before_script:
              - pip install uavcan
          script:
              - ./compile_dsdl.sh

notifications:
    email: false
