// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/pnp/32741.NodeIDAllocationData.0.1.uavcan
//
// Template:
// StructureType.j2
//
// Generated at:  2020-08-21 01:54:42.146979 UTC
// Is deprecated: no
// Fixed port ID: 32741
// Full name:     uavcan.pnp.NodeIDAllocationData
// Version:       0.1

#ifndef UAVCAN_PNP_NODE_IDALLOCATION_DATA_INCLUDED
#define UAVCAN_PNP_NODE_IDALLOCATION_DATA_INCLUDED

#include <nunavut/support/nunavut.h>
#include <uavcan/node/ID_1_0.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


typedef struct
{
    uavcan_node_ID_1_0 node_id;
    uint8_t unique_id[16];
} uavcan_pnp_NodeIDAllocationData_0_1;

/// The maximum capacity of uavcan_pnp_NodeIDAllocationData_0_1.unique_id.
static inline size_t uavcan_pnp_NodeIDAllocationData_0_1_unique_id_array_capacity(void)
{
    return (16U);
}

/// If true then uavcan_pnp_NodeIDAllocationData_0_1.unique_id's length can vary otherwise it will
/// always be the same as its capacity.
static inline bool uavcan_pnp_NodeIDAllocationData_0_1_unique_id_array_is_variable_length(void)
{
    return (false);
}

/// If uavcan_pnp_NodeIDAllocationData_0_1.unique_id is a variable length array then this is the current
/// number of items populated in the array starting from index 0. If unique_id is not a variable length array
/// then this is the same as its capacity.
static inline size_t uavcan_pnp_NodeIDAllocationData_0_1_unique_id_array_length(
    const uavcan_pnp_NodeIDAllocationData_0_1* const instance)
{
    /* Not used for fixed arrays. */
    (void)instance;
    return (16U);
}

/// Initialize an uavcan_pnp_NodeIDAllocationData_0_1 instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_pnp_NodeIDAllocationData_0_1_init(uavcan_pnp_NodeIDAllocationData_0_1* const out_instance)
{
    if (out_instance != NULL)
    {
        uavcan_node_ID_1_0_init(&(out_instance->node_id));
        memset(&(out_instance->unique_id[0]), 0, sizeof(uint8_t) * 16);
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_pnp_NodeIDAllocationData_0_1
/// instance.
#define uavcan_pnp_NodeIDAllocationData_0_1_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (18U)



/// uavcan_pnp_NodeIDAllocationData_0_1 can only be used with the fixed port identifier defined here.
#define uavcan_pnp_NodeIDAllocationData_0_1_FIXED_PORT_ID (32741U)
/// Serialization of uavcan_pnp_NodeIDAllocationData_0_1 instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_pnp_NodeIDAllocationData_0_1_serialize(const uavcan_pnp_NodeIDAllocationData_0_1* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.node.ID.1.0
    rc = uavcan_node_ID_1_0_serialize(&(in_instance->node_id), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.node.ID.1.0
    // Begin Structure: saturated uint8[16]
    
        memcpy((void*) out_buffer + (offset>> 3), (void*)in_instance->unique_id, in_instance->unique_id_length * 1);
        offset += in_instance->unique_id_length * 8;
    // End Structure: saturated uint8[16]

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_pnp_NodeIDAllocationData_0_1 instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_pnp_NodeIDAllocationData_0_1_deserialize(uavcan_pnp_NodeIDAllocationData_0_1* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.node.ID.1.0
    rc = uavcan_node_ID_1_0_deserialize(&(out_instance->node_id), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.node.ID.1.0
    // Begin Structure: saturated uint8[16]
    
    memcpy((void*)out_instance->unique_id, (void*) in_buffer + (offset >> 3), out_instance->unique_id_length * 1);
    offset += out_instance->unique_id_length * 8;
    // End Structure: saturated uint8[16]

    return offset;
}


#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_PNP_NODE_IDALLOCATION_DATA */
