// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/pnp/32742.NodeIDAllocationDataMTU8.0.1.uavcan
//
// Template:
// StructureType.j2
//
// Generated at:  2020-08-21 01:54:42.217493 UTC
// Is deprecated: no
// Fixed port ID: 32742
// Full name:     uavcan.pnp.NodeIDAllocationDataMTU8
// Version:       0.1

#ifndef UAVCAN_PNP_NODE_IDALLOCATION_DATA_MTU8_INCLUDED
#define UAVCAN_PNP_NODE_IDALLOCATION_DATA_MTU8_INCLUDED

#include <nunavut/support/nunavut.h>
#include <uavcan/node/ID_1_0.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


typedef struct
{
    uint64_t unique_id_hash;
    size_t allocated_node_id_length;
    uavcan_node_ID_1_0 allocated_node_id[1];
} uavcan_pnp_NodeIDAllocationDataMTU8_0_1;

/// The maximum capacity of uavcan_pnp_NodeIDAllocationDataMTU8_0_1.allocated_node_id.
static inline size_t uavcan_pnp_NodeIDAllocationDataMTU8_0_1_allocated_node_id_array_capacity(void)
{
    return (1U);
}

/// If true then uavcan_pnp_NodeIDAllocationDataMTU8_0_1.allocated_node_id's length can vary otherwise it will
/// always be the same as its capacity.
static inline bool uavcan_pnp_NodeIDAllocationDataMTU8_0_1_allocated_node_id_array_is_variable_length(void)
{
    return (true);
}

/// If uavcan_pnp_NodeIDAllocationDataMTU8_0_1.allocated_node_id is a variable length array then this is the current
/// number of items populated in the array starting from index 0. If allocated_node_id is not a variable length array
/// then this is the same as its capacity.
static inline size_t uavcan_pnp_NodeIDAllocationDataMTU8_0_1_allocated_node_id_array_length(
    const uavcan_pnp_NodeIDAllocationDataMTU8_0_1* const instance)
{
    return (instance == NULL) ? 0 : instance->allocated_node_id_length;
}

/// Initialize an uavcan_pnp_NodeIDAllocationDataMTU8_0_1 instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_pnp_NodeIDAllocationDataMTU8_0_1_init(uavcan_pnp_NodeIDAllocationDataMTU8_0_1* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->unique_id_hash = 0;
        out_instance->allocated_node_id_length = 0;
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_pnp_NodeIDAllocationDataMTU8_0_1
/// instance.
#define uavcan_pnp_NodeIDAllocationDataMTU8_0_1_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (9U)



/// uavcan_pnp_NodeIDAllocationDataMTU8_0_1 can only be used with the fixed port identifier defined here.
#define uavcan_pnp_NodeIDAllocationDataMTU8_0_1_FIXED_PORT_ID (32742U)
/// Serialization of uavcan_pnp_NodeIDAllocationDataMTU8_0_1 instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_pnp_NodeIDAllocationDataMTU8_0_1_serialize(const uavcan_pnp_NodeIDAllocationDataMTU8_0_1* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: truncated uint48
    
        nunavutSetUxx(out_buffer, offset, in_instance->unique_id_hash, 48);
        offset += 48;
    // End Structure: truncated uint48
    // Begin Structure: uavcan.node.ID.1.0[<=1]
    
        if (in_instance->allocated_node_id_length > 1)
        {
            return -NUNAVUT_ERR_INVALID_LEN;
        }
        nunavutSetUxx(out_buffer, offset, in_instance->allocated_node_id_length, 8);
        offset += 8;
    // End Structure: uavcan.node.ID.1.0[<=1]

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_pnp_NodeIDAllocationDataMTU8_0_1 instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_pnp_NodeIDAllocationDataMTU8_0_1_deserialize(uavcan_pnp_NodeIDAllocationDataMTU8_0_1* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: truncated uint48
    out_instance->unique_id_hash = nunavutGetU64(in_buffer, buf_size_bytes, offset, 48);
    offset += 48;
    // End Structure: truncated uint48
    // Begin Structure: uavcan.node.ID.1.0[<=1]
    
    out_instance->allocated_node_id_length = nunavutGetU8(in_buffer, buf_size_bytes, offset, 8);;
    offset += 8;
    if (out_instance->allocated_node_id_length > 1)
    {
        return -NUNAVUT_ERR_INVALID_LEN;
    }
    // End Structure: uavcan.node.ID.1.0[<=1]

    return offset;
}


#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_PNP_NODE_IDALLOCATION_DATA_MTU8 */
