// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/internet/udp/500.HandleIncomingPacket.0.1.uavcan
//
// Template:
// ServiceType.j2
//
// Generated at:  2020-08-21 01:54:43.653051 UTC
// Is deprecated: no
// Fixed port ID: 500
// Full name:     uavcan.internet.udp.HandleIncomingPacket
// Version:       0.1

#ifndef UAVCAN_INTERNET_UDP_HANDLE_INCOMING_PACKET_INCLUDED
#define UAVCAN_INTERNET_UDP_HANDLE_INCOMING_PACKET_INCLUDED

#include <nunavut/support/nunavut.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
// +------------------------------------------------------------------------------------------------------------------+
// | Begin service definitions for uavcan_internet_udp_HandleIncomingPacket_0_1
// +------------------------------------------------------------------------------------------------------------------+



typedef struct
{
    uint16_t session_id;
    size_t payload_length;
    uint8_t payload[309];
} uavcan_internet_udp_HandleIncomingPacket_0_1_Request;

/// The maximum capacity of uavcan_internet_udp_HandleIncomingPacket_0_1_Request.payload.
static inline size_t uavcan_internet_udp_HandleIncomingPacket_0_1_Request_payload_array_capacity(void)
{
    return (309U);
}

/// If true then uavcan_internet_udp_HandleIncomingPacket_0_1_Request.payload's length can vary otherwise it will
/// always be the same as its capacity.
static inline bool uavcan_internet_udp_HandleIncomingPacket_0_1_Request_payload_array_is_variable_length(void)
{
    return (true);
}

/// If uavcan_internet_udp_HandleIncomingPacket_0_1_Request.payload is a variable length array then this is the current
/// number of items populated in the array starting from index 0. If payload is not a variable length array
/// then this is the same as its capacity.
static inline size_t uavcan_internet_udp_HandleIncomingPacket_0_1_Request_payload_array_length(
    const uavcan_internet_udp_HandleIncomingPacket_0_1_Request* const instance)
{
    return (instance == NULL) ? 0 : instance->payload_length;
}

/// Initialize an uavcan_internet_udp_HandleIncomingPacket_0_1_Request instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_internet_udp_HandleIncomingPacket_0_1_Request_init(uavcan_internet_udp_HandleIncomingPacket_0_1_Request* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->session_id = 0;
        out_instance->payload_length = 0;
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_internet_udp_HandleIncomingPacket_0_1_Request
/// instance.
#define uavcan_internet_udp_HandleIncomingPacket_0_1_Request_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (313U)


// +------------------------------------------------------------------------------------------------------------------+


typedef struct
{
} uavcan_internet_udp_HandleIncomingPacket_0_1_Response;

/// Initialize an uavcan_internet_udp_HandleIncomingPacket_0_1_Response instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_internet_udp_HandleIncomingPacket_0_1_Response_init(uavcan_internet_udp_HandleIncomingPacket_0_1_Response* const out_instance)
{
    if (out_instance != NULL)
    {
        /* Ignoring 56 padding bit(s). */
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_internet_udp_HandleIncomingPacket_0_1_Response
/// instance.
#define uavcan_internet_udp_HandleIncomingPacket_0_1_Response_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (7U)



/// uavcan_internet_udp_HandleIncomingPacket_0_1 can only be used with the fixed port identifier defined here.
#define uavcan_internet_udp_HandleIncomingPacket_0_1_FIXED_PORT_ID (500U)

/// Serialization of uavcan_internet_udp_HandleIncomingPacket_0_1_Request instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_internet_udp_HandleIncomingPacket_0_1_Request_serialize(const uavcan_internet_udp_HandleIncomingPacket_0_1_Request* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint16
    
        nunavutSetUxx(out_buffer, offset, in_instance->session_id, 16);
        offset += 16;
    // End Structure: saturated uint16
    // Begin Structure: saturated uint8[<=309]
    
        if (in_instance->payload_length > 309)
        {
            return -NUNAVUT_ERR_INVALID_LEN;
        }
        nunavutSetUxx(out_buffer, offset, in_instance->payload_length, 16);
        offset += 16;
        memcpy((void*) out_buffer + (offset>> 3), (void*)in_instance->payload, in_instance->payload_length * 1);
        offset += in_instance->payload_length * 8;
    // End Structure: saturated uint8[<=309]

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_internet_udp_HandleIncomingPacket_0_1_Request instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_internet_udp_HandleIncomingPacket_0_1_Request_deserialize(uavcan_internet_udp_HandleIncomingPacket_0_1_Request* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint16
    out_instance->session_id = nunavutGetU16(in_buffer, buf_size_bytes, offset, 16);
    offset += 16;
    // End Structure: saturated uint16
    // Begin Structure: saturated uint8[<=309]
    
    out_instance->payload_length = nunavutGetU16(in_buffer, buf_size_bytes, offset, 16);;
    offset += 16;
    if (out_instance->payload_length > 309)
    {
        return -NUNAVUT_ERR_INVALID_LEN;
    }
    memcpy((void*)out_instance->payload, (void*) in_buffer + (offset >> 3), out_instance->payload_length * 1);
    offset += out_instance->payload_length * 8;
    // End Structure: saturated uint8[<=309]

    return offset;
}


/// Serialization of uavcan_internet_udp_HandleIncomingPacket_0_1_Response instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_internet_udp_HandleIncomingPacket_0_1_Response_serialize(const uavcan_internet_udp_HandleIncomingPacket_0_1_Response* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: void56
    offset += 56;
    // End Structure: void56

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_internet_udp_HandleIncomingPacket_0_1_Response instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_internet_udp_HandleIncomingPacket_0_1_Response_deserialize(uavcan_internet_udp_HandleIncomingPacket_0_1_Response* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: void56
    offset += 56;
    // End Structure: void56

    return offset;
}


// +------------------------------------------------------------------------------------------------------------------+
// | End service definitions for uavcan_internet_udp_HandleIncomingPacket_0_1
// +------------------------------------------------------------------------------------------------------------------+

#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_INTERNET_UDP_HANDLE_INCOMING_PACKET */
