// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/spear/drive/DriveCommand.1.0.uavcan
//
// Template:
// ServiceType.j2
//
// Generated at:  2020-08-21 01:54:51.071418 UTC
// Is deprecated: no
// Fixed port ID: None
// Full name:     spear.drive.DriveCommand
// Version:       1.0

#ifndef SPEAR_DRIVE_DRIVE_COMMAND_INCLUDED
#define SPEAR_DRIVE_DRIVE_COMMAND_INCLUDED

#include <nunavut/support/nunavut.h>
#include <uavcan/node/Heartbeat_1_0.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
// +------------------------------------------------------------------------------------------------------------------+
// | Begin service definitions for spear_drive_DriveCommand_1_0
// +------------------------------------------------------------------------------------------------------------------+



typedef struct
{
    uint8_t thing;
    uavcan_node_Heartbeat_1_0 id;
} spear_drive_DriveCommand_1_0_Request;

/// Initialize an spear_drive_DriveCommand_1_0_Request instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void spear_drive_DriveCommand_1_0_Request_init(spear_drive_DriveCommand_1_0_Request* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->thing = 0;
        uavcan_node_Heartbeat_1_0_init(&(out_instance->id));
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) spear_drive_DriveCommand_1_0_Request
/// instance.
#define spear_drive_DriveCommand_1_0_Request_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (8U)


// +------------------------------------------------------------------------------------------------------------------+


typedef struct
{
    uint8_t response;
} spear_drive_DriveCommand_1_0_Response;

/// Initialize an spear_drive_DriveCommand_1_0_Response instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void spear_drive_DriveCommand_1_0_Response_init(spear_drive_DriveCommand_1_0_Response* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->response = 0;
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) spear_drive_DriveCommand_1_0_Response
/// instance.
#define spear_drive_DriveCommand_1_0_Response_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (1U)



/// Serialization of spear_drive_DriveCommand_1_0_Request instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength spear_drive_DriveCommand_1_0_Request_serialize(const spear_drive_DriveCommand_1_0_Request* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint8
    
        nunavutSetUxx(out_buffer, offset, in_instance->thing, 8);
        offset += 8;
    // End Structure: saturated uint8
    // Begin Structure: uavcan.node.Heartbeat.1.0
    rc = uavcan_node_Heartbeat_1_0_serialize(&(in_instance->id), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.node.Heartbeat.1.0

    return offset;
}

/// Deserialization of byte-array encoding into spear_drive_DriveCommand_1_0_Request instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength spear_drive_DriveCommand_1_0_Request_deserialize(spear_drive_DriveCommand_1_0_Request* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint8
    out_instance->thing = nunavutGetU8(in_buffer, buf_size_bytes, offset, 8);
    offset += 8;
    // End Structure: saturated uint8
    // Begin Structure: uavcan.node.Heartbeat.1.0
    rc = uavcan_node_Heartbeat_1_0_deserialize(&(out_instance->id), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.node.Heartbeat.1.0

    return offset;
}


/// Serialization of spear_drive_DriveCommand_1_0_Response instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength spear_drive_DriveCommand_1_0_Response_serialize(const spear_drive_DriveCommand_1_0_Response* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint8
    
        nunavutSetUxx(out_buffer, offset, in_instance->response, 8);
        offset += 8;
    // End Structure: saturated uint8

    return offset;
}

/// Deserialization of byte-array encoding into spear_drive_DriveCommand_1_0_Response instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength spear_drive_DriveCommand_1_0_Response_deserialize(spear_drive_DriveCommand_1_0_Response* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint8
    out_instance->response = nunavutGetU8(in_buffer, buf_size_bytes, offset, 8);
    offset += 8;
    // End Structure: saturated uint8

    return offset;
}


// +------------------------------------------------------------------------------------------------------------------+
// | End service definitions for spear_drive_DriveCommand_1_0
// +------------------------------------------------------------------------------------------------------------------+

#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* SPEAR_DRIVE_DRIVE_COMMAND */
