// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/diagnostic/Severity.1.0.uavcan
//
// Template:
// StructureType.j2
//
// Generated at:  2020-08-21 01:54:39.822671 UTC
// Is deprecated: no
// Fixed port ID: None
// Full name:     uavcan.diagnostic.Severity
// Version:       1.0

#ifndef UAVCAN_DIAGNOSTIC_SEVERITY_INCLUDED
#define UAVCAN_DIAGNOSTIC_SEVERITY_INCLUDED

#include <nunavut/support/nunavut.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#define uavcan_diagnostic_Severity_1_0_TRACE (0)
#define uavcan_diagnostic_Severity_1_0_DEBUG (1)
#define uavcan_diagnostic_Severity_1_0_INFO (2)
#define uavcan_diagnostic_Severity_1_0_NOTICE (3)
#define uavcan_diagnostic_Severity_1_0_WARNING (4)
#define uavcan_diagnostic_Severity_1_0_ERROR (5)
#define uavcan_diagnostic_Severity_1_0_CRITICAL (6)
#define uavcan_diagnostic_Severity_1_0_ALERT (7)

typedef struct
{
    uint8_t value;
} uavcan_diagnostic_Severity_1_0;

/// Initialize an uavcan_diagnostic_Severity_1_0 instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_diagnostic_Severity_1_0_init(uavcan_diagnostic_Severity_1_0* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->value = 0;
        /* Ignoring 5 padding bit(s). */
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_diagnostic_Severity_1_0
/// instance.
#define uavcan_diagnostic_Severity_1_0_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (1U)


/// Serialization of uavcan_diagnostic_Severity_1_0 instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_diagnostic_Severity_1_0_serialize(const uavcan_diagnostic_Severity_1_0* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint3
    
        nunavutSetUxx(out_buffer, offset, in_instance->value, 3);
        offset += 3;
    // End Structure: saturated uint3
    // Begin Structure: void5
    offset += 5;
    // End Structure: void5

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_diagnostic_Severity_1_0 instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_diagnostic_Severity_1_0_deserialize(uavcan_diagnostic_Severity_1_0* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint3
    out_instance->value = nunavutGetU8(in_buffer, buf_size_bytes, offset, 3);
    offset += 3;
    // End Structure: saturated uint3
    // Begin Structure: void5
    offset += 5;
    // End Structure: void5

    return offset;
}


#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_DIAGNOSTIC_SEVERITY */
