// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/metatransport/can/ExtendedArbitrationID.0.1.uavcan
//
// Template:
// StructureType.j2
//
// Generated at:  2020-08-21 01:54:41.862866 UTC
// Is deprecated: no
// Fixed port ID: None
// Full name:     uavcan.metatransport.can.ExtendedArbitrationID
// Version:       0.1

#ifndef UAVCAN_METATRANSPORT_CAN_EXTENDED_ARBITRATION_ID_INCLUDED
#define UAVCAN_METATRANSPORT_CAN_EXTENDED_ARBITRATION_ID_INCLUDED

#include <nunavut/support/nunavut.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


typedef struct
{
    uint32_t value;
} uavcan_metatransport_can_ExtendedArbitrationID_0_1;

/// Initialize an uavcan_metatransport_can_ExtendedArbitrationID_0_1 instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_metatransport_can_ExtendedArbitrationID_0_1_init(uavcan_metatransport_can_ExtendedArbitrationID_0_1* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->value = 0;
        /* Ignoring 3 padding bit(s). */
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_metatransport_can_ExtendedArbitrationID_0_1
/// instance.
#define uavcan_metatransport_can_ExtendedArbitrationID_0_1_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (4U)


/// Serialization of uavcan_metatransport_can_ExtendedArbitrationID_0_1 instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_metatransport_can_ExtendedArbitrationID_0_1_serialize(const uavcan_metatransport_can_ExtendedArbitrationID_0_1* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: truncated uint29
    
        nunavutSetUxx(out_buffer, offset, in_instance->value, 29);
        offset += 29;
    // End Structure: truncated uint29
    // Begin Structure: void3
    offset += 3;
    // End Structure: void3

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_metatransport_can_ExtendedArbitrationID_0_1 instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_metatransport_can_ExtendedArbitrationID_0_1_deserialize(uavcan_metatransport_can_ExtendedArbitrationID_0_1* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: truncated uint29
    out_instance->value = nunavutGetU32(in_buffer, buf_size_bytes, offset, 29);
    offset += 29;
    // End Structure: truncated uint29
    // Begin Structure: void3
    offset += 3;
    // End Structure: void3

    return offset;
}


#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_METATRANSPORT_CAN_EXTENDED_ARBITRATION_ID */
