// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/pnp/cluster/390.AppendEntries.1.0.uavcan
//
// Template:
// ServiceType.j2
//
// Generated at:  2020-08-21 01:54:42.288321 UTC
// Is deprecated: no
// Fixed port ID: 390
// Full name:     uavcan.pnp.cluster.AppendEntries
// Version:       1.0

#ifndef UAVCAN_PNP_CLUSTER_APPEND_ENTRIES_INCLUDED
#define UAVCAN_PNP_CLUSTER_APPEND_ENTRIES_INCLUDED

#include <nunavut/support/nunavut.h>
#include <uavcan/pnp/cluster/Entry_1_0.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
// +------------------------------------------------------------------------------------------------------------------+
// | Begin service definitions for uavcan_pnp_cluster_AppendEntries_1_0
// +------------------------------------------------------------------------------------------------------------------+


#define uavcan_pnp_cluster_AppendEntries_1_0_Request_DEFAULT_MIN_ELECTION_TIMEOUT (2)
#define uavcan_pnp_cluster_AppendEntries_1_0_Request_DEFAULT_MAX_ELECTION_TIMEOUT (4)

typedef struct
{
    uint32_t term;
    uint32_t prev_log_term;
    uint16_t prev_log_index;
    uint16_t leader_commit;
    size_t entries_length;
    uavcan_pnp_cluster_Entry_1_0 entries[1];
} uavcan_pnp_cluster_AppendEntries_1_0_Request;

/// The maximum capacity of uavcan_pnp_cluster_AppendEntries_1_0_Request.entries.
static inline size_t uavcan_pnp_cluster_AppendEntries_1_0_Request_entries_array_capacity(void)
{
    return (1U);
}

/// If true then uavcan_pnp_cluster_AppendEntries_1_0_Request.entries's length can vary otherwise it will
/// always be the same as its capacity.
static inline bool uavcan_pnp_cluster_AppendEntries_1_0_Request_entries_array_is_variable_length(void)
{
    return (true);
}

/// If uavcan_pnp_cluster_AppendEntries_1_0_Request.entries is a variable length array then this is the current
/// number of items populated in the array starting from index 0. If entries is not a variable length array
/// then this is the same as its capacity.
static inline size_t uavcan_pnp_cluster_AppendEntries_1_0_Request_entries_array_length(
    const uavcan_pnp_cluster_AppendEntries_1_0_Request* const instance)
{
    return (instance == NULL) ? 0 : instance->entries_length;
}

/// Initialize an uavcan_pnp_cluster_AppendEntries_1_0_Request instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_pnp_cluster_AppendEntries_1_0_Request_init(uavcan_pnp_cluster_AppendEntries_1_0_Request* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->term = 0;
        out_instance->prev_log_term = 0;
        out_instance->prev_log_index = 0;
        out_instance->leader_commit = 0;
        out_instance->entries_length = 0;
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_pnp_cluster_AppendEntries_1_0_Request
/// instance.
#define uavcan_pnp_cluster_AppendEntries_1_0_Request_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (35U)


// +------------------------------------------------------------------------------------------------------------------+


typedef struct
{
    uint32_t term;
    bool success;
} uavcan_pnp_cluster_AppendEntries_1_0_Response;

/// Initialize an uavcan_pnp_cluster_AppendEntries_1_0_Response instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_pnp_cluster_AppendEntries_1_0_Response_init(uavcan_pnp_cluster_AppendEntries_1_0_Response* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->term = 0;
        out_instance->success = 0;
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_pnp_cluster_AppendEntries_1_0_Response
/// instance.
#define uavcan_pnp_cluster_AppendEntries_1_0_Response_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (5U)



/// uavcan_pnp_cluster_AppendEntries_1_0 can only be used with the fixed port identifier defined here.
#define uavcan_pnp_cluster_AppendEntries_1_0_FIXED_PORT_ID (390U)

/// Serialization of uavcan_pnp_cluster_AppendEntries_1_0_Request instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_pnp_cluster_AppendEntries_1_0_Request_serialize(const uavcan_pnp_cluster_AppendEntries_1_0_Request* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint32
    
        nunavutSetUxx(out_buffer, offset, in_instance->term, 32);
        offset += 32;
    // End Structure: saturated uint32
    // Begin Structure: saturated uint32
    
        nunavutSetUxx(out_buffer, offset, in_instance->prev_log_term, 32);
        offset += 32;
    // End Structure: saturated uint32
    // Begin Structure: saturated uint16
    
        nunavutSetUxx(out_buffer, offset, in_instance->prev_log_index, 16);
        offset += 16;
    // End Structure: saturated uint16
    // Begin Structure: saturated uint16
    
        nunavutSetUxx(out_buffer, offset, in_instance->leader_commit, 16);
        offset += 16;
    // End Structure: saturated uint16
    // Begin Structure: uavcan.pnp.cluster.Entry.1.0[<=1]
    
        if (in_instance->entries_length > 1)
        {
            return -NUNAVUT_ERR_INVALID_LEN;
        }
        nunavutSetUxx(out_buffer, offset, in_instance->entries_length, 8);
        offset += 8;
    // End Structure: uavcan.pnp.cluster.Entry.1.0[<=1]

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_pnp_cluster_AppendEntries_1_0_Request instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_pnp_cluster_AppendEntries_1_0_Request_deserialize(uavcan_pnp_cluster_AppendEntries_1_0_Request* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint32
    out_instance->term = nunavutGetU32(in_buffer, buf_size_bytes, offset, 32);
    offset += 32;
    // End Structure: saturated uint32
    // Begin Structure: saturated uint32
    out_instance->prev_log_term = nunavutGetU32(in_buffer, buf_size_bytes, offset, 32);
    offset += 32;
    // End Structure: saturated uint32
    // Begin Structure: saturated uint16
    out_instance->prev_log_index = nunavutGetU16(in_buffer, buf_size_bytes, offset, 16);
    offset += 16;
    // End Structure: saturated uint16
    // Begin Structure: saturated uint16
    out_instance->leader_commit = nunavutGetU16(in_buffer, buf_size_bytes, offset, 16);
    offset += 16;
    // End Structure: saturated uint16
    // Begin Structure: uavcan.pnp.cluster.Entry.1.0[<=1]
    
    out_instance->entries_length = nunavutGetU8(in_buffer, buf_size_bytes, offset, 8);;
    offset += 8;
    if (out_instance->entries_length > 1)
    {
        return -NUNAVUT_ERR_INVALID_LEN;
    }
    // End Structure: uavcan.pnp.cluster.Entry.1.0[<=1]

    return offset;
}


/// Serialization of uavcan_pnp_cluster_AppendEntries_1_0_Response instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_pnp_cluster_AppendEntries_1_0_Response_serialize(const uavcan_pnp_cluster_AppendEntries_1_0_Response* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint32
    
        nunavutSetUxx(out_buffer, offset, in_instance->term, 32);
        offset += 32;
    // End Structure: saturated uint32
    // Begin Structure: saturated bool
    
        nunavutSetBit(out_buffer, offset, in_instance->success);
        offset += 1;
    // End Structure: saturated bool

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_pnp_cluster_AppendEntries_1_0_Response instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_pnp_cluster_AppendEntries_1_0_Response_deserialize(uavcan_pnp_cluster_AppendEntries_1_0_Response* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint32
    out_instance->term = nunavutGetU32(in_buffer, buf_size_bytes, offset, 32);
    offset += 32;
    // End Structure: saturated uint32
    // Begin Structure: saturated bool
    out_instance->success = nunavutGetBit(in_buffer, buf_size_bytes, offset);
    offset += 1;
    // End Structure: saturated bool

    return offset;
}


// +------------------------------------------------------------------------------------------------------------------+
// | End service definitions for uavcan_pnp_cluster_AppendEntries_1_0
// +------------------------------------------------------------------------------------------------------------------+

#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_PNP_CLUSTER_APPEND_ENTRIES */
