// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/pnp/cluster/391.RequestVote.1.0.uavcan
//
// Template:
// ServiceType.j2
//
// Generated at:  2020-08-21 01:54:42.573944 UTC
// Is deprecated: no
// Fixed port ID: 391
// Full name:     uavcan.pnp.cluster.RequestVote
// Version:       1.0

#ifndef UAVCAN_PNP_CLUSTER_REQUEST_VOTE_INCLUDED
#define UAVCAN_PNP_CLUSTER_REQUEST_VOTE_INCLUDED

#include <nunavut/support/nunavut.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
// +------------------------------------------------------------------------------------------------------------------+
// | Begin service definitions for uavcan_pnp_cluster_RequestVote_1_0
// +------------------------------------------------------------------------------------------------------------------+



typedef struct
{
    uint32_t term;
    uint32_t last_log_term;
    uint16_t last_log_index;
} uavcan_pnp_cluster_RequestVote_1_0_Request;

/// Initialize an uavcan_pnp_cluster_RequestVote_1_0_Request instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_pnp_cluster_RequestVote_1_0_Request_init(uavcan_pnp_cluster_RequestVote_1_0_Request* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->term = 0;
        out_instance->last_log_term = 0;
        out_instance->last_log_index = 0;
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_pnp_cluster_RequestVote_1_0_Request
/// instance.
#define uavcan_pnp_cluster_RequestVote_1_0_Request_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (10U)


// +------------------------------------------------------------------------------------------------------------------+


typedef struct
{
    uint32_t term;
    bool vote_granted;
} uavcan_pnp_cluster_RequestVote_1_0_Response;

/// Initialize an uavcan_pnp_cluster_RequestVote_1_0_Response instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_pnp_cluster_RequestVote_1_0_Response_init(uavcan_pnp_cluster_RequestVote_1_0_Response* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->term = 0;
        out_instance->vote_granted = 0;
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_pnp_cluster_RequestVote_1_0_Response
/// instance.
#define uavcan_pnp_cluster_RequestVote_1_0_Response_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (5U)



/// uavcan_pnp_cluster_RequestVote_1_0 can only be used with the fixed port identifier defined here.
#define uavcan_pnp_cluster_RequestVote_1_0_FIXED_PORT_ID (391U)

/// Serialization of uavcan_pnp_cluster_RequestVote_1_0_Request instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_pnp_cluster_RequestVote_1_0_Request_serialize(const uavcan_pnp_cluster_RequestVote_1_0_Request* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint32
    
        nunavutSetUxx(out_buffer, offset, in_instance->term, 32);
        offset += 32;
    // End Structure: saturated uint32
    // Begin Structure: saturated uint32
    
        nunavutSetUxx(out_buffer, offset, in_instance->last_log_term, 32);
        offset += 32;
    // End Structure: saturated uint32
    // Begin Structure: saturated uint16
    
        nunavutSetUxx(out_buffer, offset, in_instance->last_log_index, 16);
        offset += 16;
    // End Structure: saturated uint16

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_pnp_cluster_RequestVote_1_0_Request instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_pnp_cluster_RequestVote_1_0_Request_deserialize(uavcan_pnp_cluster_RequestVote_1_0_Request* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint32
    out_instance->term = nunavutGetU32(in_buffer, buf_size_bytes, offset, 32);
    offset += 32;
    // End Structure: saturated uint32
    // Begin Structure: saturated uint32
    out_instance->last_log_term = nunavutGetU32(in_buffer, buf_size_bytes, offset, 32);
    offset += 32;
    // End Structure: saturated uint32
    // Begin Structure: saturated uint16
    out_instance->last_log_index = nunavutGetU16(in_buffer, buf_size_bytes, offset, 16);
    offset += 16;
    // End Structure: saturated uint16

    return offset;
}


/// Serialization of uavcan_pnp_cluster_RequestVote_1_0_Response instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_pnp_cluster_RequestVote_1_0_Response_serialize(const uavcan_pnp_cluster_RequestVote_1_0_Response* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint32
    
        nunavutSetUxx(out_buffer, offset, in_instance->term, 32);
        offset += 32;
    // End Structure: saturated uint32
    // Begin Structure: saturated bool
    
        nunavutSetBit(out_buffer, offset, in_instance->vote_granted);
        offset += 1;
    // End Structure: saturated bool

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_pnp_cluster_RequestVote_1_0_Response instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_pnp_cluster_RequestVote_1_0_Response_deserialize(uavcan_pnp_cluster_RequestVote_1_0_Response* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint32
    out_instance->term = nunavutGetU32(in_buffer, buf_size_bytes, offset, 32);
    offset += 32;
    // End Structure: saturated uint32
    // Begin Structure: saturated bool
    out_instance->vote_granted = nunavutGetBit(in_buffer, buf_size_bytes, offset);
    offset += 1;
    // End Structure: saturated bool

    return offset;
}


// +------------------------------------------------------------------------------------------------------------------+
// | End service definitions for uavcan_pnp_cluster_RequestVote_1_0
// +------------------------------------------------------------------------------------------------------------------+

#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_PNP_CLUSTER_REQUEST_VOTE */
