// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/file/405.GetInfo.0.1.uavcan
//
// Template:
// ServiceType.j2
//
// Generated at:  2020-08-21 01:54:43.954588 UTC
// Is deprecated: no
// Fixed port ID: 405
// Full name:     uavcan.file.GetInfo
// Version:       0.1

#ifndef UAVCAN_FILE_GET_INFO_INCLUDED
#define UAVCAN_FILE_GET_INFO_INCLUDED

#include <nunavut/support/nunavut.h>
#include <uavcan/file/Error_1_0.h>
#include <uavcan/file/Path_1_0.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
// +------------------------------------------------------------------------------------------------------------------+
// | Begin service definitions for uavcan_file_GetInfo_0_1
// +------------------------------------------------------------------------------------------------------------------+



typedef struct
{
    uavcan_file_Path_1_0 path;
} uavcan_file_GetInfo_0_1_Request;

/// Initialize an uavcan_file_GetInfo_0_1_Request instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_file_GetInfo_0_1_Request_init(uavcan_file_GetInfo_0_1_Request* const out_instance)
{
    if (out_instance != NULL)
    {
        uavcan_file_Path_1_0_init(&(out_instance->path));
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_file_GetInfo_0_1_Request
/// instance.
#define uavcan_file_GetInfo_0_1_Request_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (113U)


// +------------------------------------------------------------------------------------------------------------------+


typedef struct
{
    uavcan_file_Error_1_0 _error;
    uint64_t size;
    uint64_t unix_timestamp_of_last_modification;
    bool is_file_not_directory;
    bool is_link;
    bool is_readable;
    bool is_writeable;
} uavcan_file_GetInfo_0_1_Response;

/// Initialize an uavcan_file_GetInfo_0_1_Response instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_file_GetInfo_0_1_Response_init(uavcan_file_GetInfo_0_1_Response* const out_instance)
{
    if (out_instance != NULL)
    {
        uavcan_file_Error_1_0_init(&(out_instance->_error));
        out_instance->size = 0;
        out_instance->unix_timestamp_of_last_modification = 0;
        out_instance->is_file_not_directory = 0;
        out_instance->is_link = 0;
        out_instance->is_readable = 0;
        out_instance->is_writeable = 0;
        /* Ignoring 4 padding bit(s). */
        /* Ignoring 64 padding bit(s). */
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_file_GetInfo_0_1_Response
/// instance.
#define uavcan_file_GetInfo_0_1_Response_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (21U)



/// uavcan_file_GetInfo_0_1 can only be used with the fixed port identifier defined here.
#define uavcan_file_GetInfo_0_1_FIXED_PORT_ID (405U)

/// Serialization of uavcan_file_GetInfo_0_1_Request instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_GetInfo_0_1_Request_serialize(const uavcan_file_GetInfo_0_1_Request* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.file.Path.1.0
    rc = uavcan_file_Path_1_0_serialize(&(in_instance->path), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.file.Path.1.0

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_file_GetInfo_0_1_Request instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_GetInfo_0_1_Request_deserialize(uavcan_file_GetInfo_0_1_Request* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.file.Path.1.0
    rc = uavcan_file_Path_1_0_deserialize(&(out_instance->path), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.file.Path.1.0

    return offset;
}


/// Serialization of uavcan_file_GetInfo_0_1_Response instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_GetInfo_0_1_Response_serialize(const uavcan_file_GetInfo_0_1_Response* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.file.Error.1.0
    rc = uavcan_file_Error_1_0_serialize(&(in_instance->_error), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.file.Error.1.0
    // Begin Structure: truncated uint40
    
        nunavutSetUxx(out_buffer, offset, in_instance->size, 40);
        offset += 40;
    // End Structure: truncated uint40
    // Begin Structure: truncated uint40
    
        nunavutSetUxx(out_buffer, offset, in_instance->unix_timestamp_of_last_modification, 40);
        offset += 40;
    // End Structure: truncated uint40
    // Begin Structure: saturated bool
    
        nunavutSetBit(out_buffer, offset, in_instance->is_file_not_directory);
        offset += 1;
    // End Structure: saturated bool
    // Begin Structure: saturated bool
    
        nunavutSetBit(out_buffer, offset, in_instance->is_link);
        offset += 1;
    // End Structure: saturated bool
    // Begin Structure: saturated bool
    
        nunavutSetBit(out_buffer, offset, in_instance->is_readable);
        offset += 1;
    // End Structure: saturated bool
    // Begin Structure: saturated bool
    
        nunavutSetBit(out_buffer, offset, in_instance->is_writeable);
        offset += 1;
    // End Structure: saturated bool
    // Begin Structure: void4
    offset += 4;
    // End Structure: void4
    // Begin Structure: void64
    offset += 64;
    // End Structure: void64

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_file_GetInfo_0_1_Response instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_GetInfo_0_1_Response_deserialize(uavcan_file_GetInfo_0_1_Response* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.file.Error.1.0
    rc = uavcan_file_Error_1_0_deserialize(&(out_instance->_error), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.file.Error.1.0
    // Begin Structure: truncated uint40
    out_instance->size = nunavutGetU64(in_buffer, buf_size_bytes, offset, 40);
    offset += 40;
    // End Structure: truncated uint40
    // Begin Structure: truncated uint40
    out_instance->unix_timestamp_of_last_modification = nunavutGetU64(in_buffer, buf_size_bytes, offset, 40);
    offset += 40;
    // End Structure: truncated uint40
    // Begin Structure: saturated bool
    out_instance->is_file_not_directory = nunavutGetBit(in_buffer, buf_size_bytes, offset);
    offset += 1;
    // End Structure: saturated bool
    // Begin Structure: saturated bool
    out_instance->is_link = nunavutGetBit(in_buffer, buf_size_bytes, offset);
    offset += 1;
    // End Structure: saturated bool
    // Begin Structure: saturated bool
    out_instance->is_readable = nunavutGetBit(in_buffer, buf_size_bytes, offset);
    offset += 1;
    // End Structure: saturated bool
    // Begin Structure: saturated bool
    out_instance->is_writeable = nunavutGetBit(in_buffer, buf_size_bytes, offset);
    offset += 1;
    // End Structure: saturated bool
    // Begin Structure: void4
    offset += 4;
    // End Structure: void4
    // Begin Structure: void64
    offset += 64;
    // End Structure: void64

    return offset;
}


// +------------------------------------------------------------------------------------------------------------------+
// | End service definitions for uavcan_file_GetInfo_0_1
// +------------------------------------------------------------------------------------------------------------------+

#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_FILE_GET_INFO */
