// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/file/406.List.0.1.uavcan
//
// Template:
// ServiceType.j2
//
// Generated at:  2020-08-21 01:54:44.090885 UTC
// Is deprecated: no
// Fixed port ID: 406
// Full name:     uavcan.file.List
// Version:       0.1

#ifndef UAVCAN_FILE_LIST_INCLUDED
#define UAVCAN_FILE_LIST_INCLUDED

#include <nunavut/support/nunavut.h>
#include <uavcan/file/Path_1_0.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
// +------------------------------------------------------------------------------------------------------------------+
// | Begin service definitions for uavcan_file_List_0_1
// +------------------------------------------------------------------------------------------------------------------+



typedef struct
{
    uint32_t entry_index;
    uavcan_file_Path_1_0 directory_path;
} uavcan_file_List_0_1_Request;

/// Initialize an uavcan_file_List_0_1_Request instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_file_List_0_1_Request_init(uavcan_file_List_0_1_Request* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->entry_index = 0;
        /* Ignoring 32 padding bit(s). */
        uavcan_file_Path_1_0_init(&(out_instance->directory_path));
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_file_List_0_1_Request
/// instance.
#define uavcan_file_List_0_1_Request_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (121U)


// +------------------------------------------------------------------------------------------------------------------+


typedef struct
{
    uavcan_file_Path_1_0 entry_base_name;
} uavcan_file_List_0_1_Response;

/// Initialize an uavcan_file_List_0_1_Response instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_file_List_0_1_Response_init(uavcan_file_List_0_1_Response* const out_instance)
{
    if (out_instance != NULL)
    {
        /* Ignoring 32 padding bit(s). */
        uavcan_file_Path_1_0_init(&(out_instance->entry_base_name));
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_file_List_0_1_Response
/// instance.
#define uavcan_file_List_0_1_Response_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (117U)



/// uavcan_file_List_0_1 can only be used with the fixed port identifier defined here.
#define uavcan_file_List_0_1_FIXED_PORT_ID (406U)

/// Serialization of uavcan_file_List_0_1_Request instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_List_0_1_Request_serialize(const uavcan_file_List_0_1_Request* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint32
    
        nunavutSetUxx(out_buffer, offset, in_instance->entry_index, 32);
        offset += 32;
    // End Structure: saturated uint32
    // Begin Structure: void32
    offset += 32;
    // End Structure: void32
    // Begin Structure: uavcan.file.Path.1.0
    rc = uavcan_file_Path_1_0_serialize(&(in_instance->directory_path), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.file.Path.1.0

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_file_List_0_1_Request instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_List_0_1_Request_deserialize(uavcan_file_List_0_1_Request* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint32
    out_instance->entry_index = nunavutGetU32(in_buffer, buf_size_bytes, offset, 32);
    offset += 32;
    // End Structure: saturated uint32
    // Begin Structure: void32
    offset += 32;
    // End Structure: void32
    // Begin Structure: uavcan.file.Path.1.0
    rc = uavcan_file_Path_1_0_deserialize(&(out_instance->directory_path), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.file.Path.1.0

    return offset;
}


/// Serialization of uavcan_file_List_0_1_Response instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_List_0_1_Response_serialize(const uavcan_file_List_0_1_Response* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: void32
    offset += 32;
    // End Structure: void32
    // Begin Structure: uavcan.file.Path.1.0
    rc = uavcan_file_Path_1_0_serialize(&(in_instance->entry_base_name), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.file.Path.1.0

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_file_List_0_1_Response instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_List_0_1_Response_deserialize(uavcan_file_List_0_1_Response* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: void32
    offset += 32;
    // End Structure: void32
    // Begin Structure: uavcan.file.Path.1.0
    rc = uavcan_file_Path_1_0_deserialize(&(out_instance->entry_base_name), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.file.Path.1.0

    return offset;
}


// +------------------------------------------------------------------------------------------------------------------+
// | End service definitions for uavcan_file_List_0_1
// +------------------------------------------------------------------------------------------------------------------+

#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_FILE_LIST */
