// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/file/407.Modify.1.0.uavcan
//
// Template:
// ServiceType.j2
//
// Generated at:  2020-08-21 01:54:44.228243 UTC
// Is deprecated: no
// Fixed port ID: 407
// Full name:     uavcan.file.Modify
// Version:       1.0

#ifndef UAVCAN_FILE_MODIFY_INCLUDED
#define UAVCAN_FILE_MODIFY_INCLUDED

#include <nunavut/support/nunavut.h>
#include <uavcan/file/Error_1_0.h>
#include <uavcan/file/Path_1_0.h>
#include <stdbool.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
// +------------------------------------------------------------------------------------------------------------------+
// | Begin service definitions for uavcan_file_Modify_1_0
// +------------------------------------------------------------------------------------------------------------------+



typedef struct
{
    bool preserve_source;
    bool overwrite_destination;
    uavcan_file_Path_1_0 source;
    uavcan_file_Path_1_0 destination;
} uavcan_file_Modify_1_0_Request;

/// Initialize an uavcan_file_Modify_1_0_Request instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_file_Modify_1_0_Request_init(uavcan_file_Modify_1_0_Request* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->preserve_source = 0;
        out_instance->overwrite_destination = 0;
        /* Ignoring 30 padding bit(s). */
        uavcan_file_Path_1_0_init(&(out_instance->source));
        uavcan_file_Path_1_0_init(&(out_instance->destination));
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_file_Modify_1_0_Request
/// instance.
#define uavcan_file_Modify_1_0_Request_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (230U)


// +------------------------------------------------------------------------------------------------------------------+


typedef struct
{
    uavcan_file_Error_1_0 _error;
} uavcan_file_Modify_1_0_Response;

/// Initialize an uavcan_file_Modify_1_0_Response instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_file_Modify_1_0_Response_init(uavcan_file_Modify_1_0_Response* const out_instance)
{
    if (out_instance != NULL)
    {
        uavcan_file_Error_1_0_init(&(out_instance->_error));
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_file_Modify_1_0_Response
/// instance.
#define uavcan_file_Modify_1_0_Response_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (2U)



/// uavcan_file_Modify_1_0 can only be used with the fixed port identifier defined here.
#define uavcan_file_Modify_1_0_FIXED_PORT_ID (407U)

/// Serialization of uavcan_file_Modify_1_0_Request instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_Modify_1_0_Request_serialize(const uavcan_file_Modify_1_0_Request* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated bool
    
        nunavutSetBit(out_buffer, offset, in_instance->preserve_source);
        offset += 1;
    // End Structure: saturated bool
    // Begin Structure: saturated bool
    
        nunavutSetBit(out_buffer, offset, in_instance->overwrite_destination);
        offset += 1;
    // End Structure: saturated bool
    // Begin Structure: void30
    offset += 30;
    // End Structure: void30
    // Begin Structure: uavcan.file.Path.1.0
    rc = uavcan_file_Path_1_0_serialize(&(in_instance->source), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.file.Path.1.0
    // Begin Structure: uavcan.file.Path.1.0
    rc = uavcan_file_Path_1_0_serialize(&(in_instance->destination), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.file.Path.1.0

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_file_Modify_1_0_Request instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_Modify_1_0_Request_deserialize(uavcan_file_Modify_1_0_Request* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated bool
    out_instance->preserve_source = nunavutGetBit(in_buffer, buf_size_bytes, offset);
    offset += 1;
    // End Structure: saturated bool
    // Begin Structure: saturated bool
    out_instance->overwrite_destination = nunavutGetBit(in_buffer, buf_size_bytes, offset);
    offset += 1;
    // End Structure: saturated bool
    // Begin Structure: void30
    offset += 30;
    // End Structure: void30
    // Begin Structure: uavcan.file.Path.1.0
    rc = uavcan_file_Path_1_0_deserialize(&(out_instance->source), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.file.Path.1.0
    // Begin Structure: uavcan.file.Path.1.0
    rc = uavcan_file_Path_1_0_deserialize(&(out_instance->destination), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.file.Path.1.0

    return offset;
}


/// Serialization of uavcan_file_Modify_1_0_Response instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_Modify_1_0_Response_serialize(const uavcan_file_Modify_1_0_Response* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.file.Error.1.0
    rc = uavcan_file_Error_1_0_serialize(&(in_instance->_error), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.file.Error.1.0

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_file_Modify_1_0_Response instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_Modify_1_0_Response_deserialize(uavcan_file_Modify_1_0_Response* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.file.Error.1.0
    rc = uavcan_file_Error_1_0_deserialize(&(out_instance->_error), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.file.Error.1.0

    return offset;
}


// +------------------------------------------------------------------------------------------------------------------+
// | End service definitions for uavcan_file_Modify_1_0
// +------------------------------------------------------------------------------------------------------------------+

#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_FILE_MODIFY */
