// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/file/408.Read.1.0.uavcan
//
// Template:
// ServiceType.j2
//
// Generated at:  2020-08-21 01:54:44.448779 UTC
// Is deprecated: no
// Fixed port ID: 408
// Full name:     uavcan.file.Read
// Version:       1.0

#ifndef UAVCAN_FILE_READ_INCLUDED
#define UAVCAN_FILE_READ_INCLUDED

#include <nunavut/support/nunavut.h>
#include <uavcan/file/Error_1_0.h>
#include <uavcan/file/Path_1_0.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
// +------------------------------------------------------------------------------------------------------------------+
// | Begin service definitions for uavcan_file_Read_1_0
// +------------------------------------------------------------------------------------------------------------------+



typedef struct
{
    uint64_t offset;
    uavcan_file_Path_1_0 path;
} uavcan_file_Read_1_0_Request;

/// Initialize an uavcan_file_Read_1_0_Request instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_file_Read_1_0_Request_init(uavcan_file_Read_1_0_Request* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->offset = 0;
        uavcan_file_Path_1_0_init(&(out_instance->path));
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_file_Read_1_0_Request
/// instance.
#define uavcan_file_Read_1_0_Request_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (118U)


// +------------------------------------------------------------------------------------------------------------------+


typedef struct
{
    uavcan_file_Error_1_0 _error;
    size_t data_length;
    uint8_t data[256];
} uavcan_file_Read_1_0_Response;

/// The maximum capacity of uavcan_file_Read_1_0_Response.data.
static inline size_t uavcan_file_Read_1_0_Response_data_array_capacity(void)
{
    return (256U);
}

/// If true then uavcan_file_Read_1_0_Response.data's length can vary otherwise it will
/// always be the same as its capacity.
static inline bool uavcan_file_Read_1_0_Response_data_array_is_variable_length(void)
{
    return (true);
}

/// If uavcan_file_Read_1_0_Response.data is a variable length array then this is the current
/// number of items populated in the array starting from index 0. If data is not a variable length array
/// then this is the same as its capacity.
static inline size_t uavcan_file_Read_1_0_Response_data_array_length(
    const uavcan_file_Read_1_0_Response* const instance)
{
    return (instance == NULL) ? 0 : instance->data_length;
}

/// Initialize an uavcan_file_Read_1_0_Response instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_file_Read_1_0_Response_init(uavcan_file_Read_1_0_Response* const out_instance)
{
    if (out_instance != NULL)
    {
        uavcan_file_Error_1_0_init(&(out_instance->_error));
        out_instance->data_length = 0;
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_file_Read_1_0_Response
/// instance.
#define uavcan_file_Read_1_0_Response_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (260U)



/// uavcan_file_Read_1_0 can only be used with the fixed port identifier defined here.
#define uavcan_file_Read_1_0_FIXED_PORT_ID (408U)

/// Serialization of uavcan_file_Read_1_0_Request instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_Read_1_0_Request_serialize(const uavcan_file_Read_1_0_Request* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: truncated uint40
    
        nunavutSetUxx(out_buffer, offset, in_instance->offset, 40);
        offset += 40;
    // End Structure: truncated uint40
    // Begin Structure: uavcan.file.Path.1.0
    rc = uavcan_file_Path_1_0_serialize(&(in_instance->path), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.file.Path.1.0

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_file_Read_1_0_Request instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_Read_1_0_Request_deserialize(uavcan_file_Read_1_0_Request* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: truncated uint40
    out_instance->offset = nunavutGetU64(in_buffer, buf_size_bytes, offset, 40);
    offset += 40;
    // End Structure: truncated uint40
    // Begin Structure: uavcan.file.Path.1.0
    rc = uavcan_file_Path_1_0_deserialize(&(out_instance->path), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.file.Path.1.0

    return offset;
}


/// Serialization of uavcan_file_Read_1_0_Response instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_Read_1_0_Response_serialize(const uavcan_file_Read_1_0_Response* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.file.Error.1.0
    rc = uavcan_file_Error_1_0_serialize(&(in_instance->_error), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.file.Error.1.0
    // Begin Structure: saturated uint8[<=256]
    
        if (in_instance->data_length > 256)
        {
            return -NUNAVUT_ERR_INVALID_LEN;
        }
        nunavutSetUxx(out_buffer, offset, in_instance->data_length, 16);
        offset += 16;
        memcpy((void*) out_buffer + (offset>> 3), (void*)in_instance->data, in_instance->data_length * 1);
        offset += in_instance->data_length * 8;
    // End Structure: saturated uint8[<=256]

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_file_Read_1_0_Response instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_file_Read_1_0_Response_deserialize(uavcan_file_Read_1_0_Response* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.file.Error.1.0
    rc = uavcan_file_Error_1_0_deserialize(&(out_instance->_error), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.file.Error.1.0
    // Begin Structure: saturated uint8[<=256]
    
    out_instance->data_length = nunavutGetU16(in_buffer, buf_size_bytes, offset, 16);;
    offset += 16;
    if (out_instance->data_length > 256)
    {
        return -NUNAVUT_ERR_INVALID_LEN;
    }
    memcpy((void*)out_instance->data, (void*) in_buffer + (offset >> 3), out_instance->data_length * 1);
    offset += out_instance->data_length * 8;
    // End Structure: saturated uint8[<=256]

    return offset;
}


// +------------------------------------------------------------------------------------------------------------------+
// | End service definitions for uavcan_file_Read_1_0
// +------------------------------------------------------------------------------------------------------------------+

#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_FILE_READ */
