// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/node/port/433.GetStatistics.0.1.uavcan
//
// Template:
// ServiceType.j2
//
// Generated at:  2020-08-21 01:54:40.762054 UTC
// Is deprecated: no
// Fixed port ID: 433
// Full name:     uavcan.node.port.GetStatistics
// Version:       0.1

#ifndef UAVCAN_NODE_PORT_GET_STATISTICS_INCLUDED
#define UAVCAN_NODE_PORT_GET_STATISTICS_INCLUDED

#include <nunavut/support/nunavut.h>
#include <uavcan/node/IOStatistics_0_1.h>
#include <uavcan/node/port/ID_1_0.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
// +------------------------------------------------------------------------------------------------------------------+
// | Begin service definitions for uavcan_node_port_GetStatistics_0_1
// +------------------------------------------------------------------------------------------------------------------+



typedef struct
{
    uavcan_node_port_ID_1_0 port_id;
} uavcan_node_port_GetStatistics_0_1_Request;

/// Initialize an uavcan_node_port_GetStatistics_0_1_Request instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_node_port_GetStatistics_0_1_Request_init(uavcan_node_port_GetStatistics_0_1_Request* const out_instance)
{
    if (out_instance != NULL)
    {
        uavcan_node_port_ID_1_0_init(&(out_instance->port_id));
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_node_port_GetStatistics_0_1_Request
/// instance.
#define uavcan_node_port_GetStatistics_0_1_Request_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (3U)


// +------------------------------------------------------------------------------------------------------------------+


typedef struct
{
    uavcan_node_IOStatistics_0_1 statistics;
} uavcan_node_port_GetStatistics_0_1_Response;

/// Initialize an uavcan_node_port_GetStatistics_0_1_Response instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_node_port_GetStatistics_0_1_Response_init(uavcan_node_port_GetStatistics_0_1_Response* const out_instance)
{
    if (out_instance != NULL)
    {
        uavcan_node_IOStatistics_0_1_init(&(out_instance->statistics));
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_node_port_GetStatistics_0_1_Response
/// instance.
#define uavcan_node_port_GetStatistics_0_1_Response_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (15U)



/// uavcan_node_port_GetStatistics_0_1 can only be used with the fixed port identifier defined here.
#define uavcan_node_port_GetStatistics_0_1_FIXED_PORT_ID (433U)

/// Serialization of uavcan_node_port_GetStatistics_0_1_Request instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_node_port_GetStatistics_0_1_Request_serialize(const uavcan_node_port_GetStatistics_0_1_Request* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.node.port.ID.1.0
    rc = uavcan_node_port_ID_1_0_serialize(&(in_instance->port_id), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.node.port.ID.1.0

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_node_port_GetStatistics_0_1_Request instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_node_port_GetStatistics_0_1_Request_deserialize(uavcan_node_port_GetStatistics_0_1_Request* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.node.port.ID.1.0
    rc = uavcan_node_port_ID_1_0_deserialize(&(out_instance->port_id), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.node.port.ID.1.0

    return offset;
}


/// Serialization of uavcan_node_port_GetStatistics_0_1_Response instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_node_port_GetStatistics_0_1_Response_serialize(const uavcan_node_port_GetStatistics_0_1_Response* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.node.IOStatistics.0.1
    rc = uavcan_node_IOStatistics_0_1_serialize(&(in_instance->statistics), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.node.IOStatistics.0.1

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_node_port_GetStatistics_0_1_Response instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_node_port_GetStatistics_0_1_Response_deserialize(uavcan_node_port_GetStatistics_0_1_Response* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.node.IOStatistics.0.1
    rc = uavcan_node_IOStatistics_0_1_deserialize(&(out_instance->statistics), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.node.IOStatistics.0.1

    return offset;
}


// +------------------------------------------------------------------------------------------------------------------+
// | End service definitions for uavcan_node_port_GetStatistics_0_1
// +------------------------------------------------------------------------------------------------------------------+

#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_NODE_PORT_GET_STATISTICS */
