// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/node/port/ID.1.0.uavcan
//
// Template:
// UnionType.j2
//
// Generated at:  2020-08-21 01:54:40.893474 UTC
// Is deprecated: no
// Fixed port ID: None
// Full name:     uavcan.node.port.ID
// Version:       1.0

#ifndef UAVCAN_NODE_PORT_ID_INCLUDED
#define UAVCAN_NODE_PORT_ID_INCLUDED

#include <nunavut/support/nunavut.h>
#include <uavcan/node/port/ServiceID_1_0.h>
#include <uavcan/node/port/SubjectID_1_0.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


typedef struct
{    
    uint8_t _tag_;
    union
    {
        uavcan_node_port_SubjectID_1_0 subject_id;
        uavcan_node_port_ServiceID_1_0 service_id;
    };
} uavcan_node_port_ID_1_0;

/// Initialize an uavcan_node_port_ID_1_0 instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_node_port_ID_1_0_init(uavcan_node_port_ID_1_0* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->_tag_ = 0;
        uavcan_node_port_SubjectID_1_0_init(&(out_instance->subject_id));
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_node_port_ID_1_0
/// instance.
#define uavcan_node_port_ID_1_0_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (3U)


/// Determine if a given uavcan_node_port_ID_1_0 tagged union is currently tagged as
/// subject_id. If so, then uavcan_node_port_ID_1_0->subject_id
/// can be accessed safely.
static inline bool uavcan_node_port_ID_1_0_is_subject_id(const uavcan_node_port_ID_1_0* const tagged_union_ptr)
{
    return ((tagged_union_ptr != NULL) && tagged_union_ptr->_tag_ == 0);
}

/// Determine if a given uavcan_node_port_ID_1_0 tagged union is currently tagged as
/// service_id. If so, then uavcan_node_port_ID_1_0->service_id
/// can be accessed safely.
static inline bool uavcan_node_port_ID_1_0_is_service_id(const uavcan_node_port_ID_1_0* const tagged_union_ptr)
{
    return ((tagged_union_ptr != NULL) && tagged_union_ptr->_tag_ == 1);
}

/// Serialization of uavcan_node_port_ID_1_0 instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_node_port_ID_1_0_serialize(const uavcan_node_port_ID_1_0* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Union: uavcan_node_port_ID_1_0
    nunavutSetUxx(out_buffer, offset, in_instance->_tag_, 8);
    offset += 8;
    if (uavcan_node_port_ID_1_0_is_subject_id(in_instance))
    {
        rc = uavcan_node_port_SubjectID_1_0_serialize(&(in_instance->subject_id), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    }
    else if (uavcan_node_port_ID_1_0_is_service_id(in_instance))
    {
        rc = uavcan_node_port_ServiceID_1_0_serialize(&(in_instance->service_id), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    }
    else
    {
        return -NUNAVUT_ERR_INVALID_TAG;
    }
    // End Union: uavcan_node_port_ID_1_0

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_node_port_ID_1_0 instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_node_port_ID_1_0_deserialize(uavcan_node_port_ID_1_0* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Union: uavcan.node.port.ID.1.0
    out_instance->_tag_ = nunavutGetU8(in_buffer, buf_size_bytes, offset, 8);
    offset += 8;
    if (uavcan_node_port_ID_1_0_is_subject_id(out_instance))
    {
        rc = uavcan_node_port_SubjectID_1_0_deserialize(&(out_instance->subject_id), offset, in_buffer, buf_size_bytes);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    }
    else if (uavcan_node_port_ID_1_0_is_service_id(out_instance))
    {
        rc = uavcan_node_port_ServiceID_1_0_deserialize(&(out_instance->service_id), offset, in_buffer, buf_size_bytes);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    }
    else
    {
        return -NUNAVUT_ERR_INVALID_TAG;
    }
    // End Union: uavcan.node.port.ID.1.0

    return offset;
}



#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_NODE_PORT_ID */
