/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/isthatme/Documents/Clubs/SPEAR/dsdl/spear/general/20200.PpmMessage.uavcan
 */

#ifndef SPEAR_GENERAL_PPMMESSAGE_HPP_INCLUDED
#define SPEAR_GENERAL_PPMMESSAGE_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# DSDL definitions for ppm inputs
# No more than 8 channels by spec

int32[<=8] channel_data
******************************************************************************/

/********************* DSDL signature source definition ***********************
spear.general.PpmMessage
saturated int32[<=8] channel_data
******************************************************************************/

#undef channel_data

namespace spear
{
namespace general
{

template <int _tmpl>
struct UAVCAN_EXPORT PpmMessage_
{
    typedef const PpmMessage_<_tmpl>& ParameterType;
    typedef PpmMessage_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::Array< ::uavcan::IntegerSpec< 32, ::uavcan::SignednessSigned, ::uavcan::CastModeSaturate >, ::uavcan::ArrayModeDynamic, 8 > channel_data;
    };

    enum
    {
        MinBitLen
            = FieldTypes::channel_data::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::channel_data::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::channel_data >::Type channel_data;

    PpmMessage_()
        : channel_data()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<260 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 20200 };

    static const char* getDataTypeFullName()
    {
        return "spear.general.PpmMessage";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool PpmMessage_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        channel_data == rhs.channel_data;
}

template <int _tmpl>
bool PpmMessage_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(channel_data, rhs.channel_data);
}

template <int _tmpl>
int PpmMessage_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::channel_data::encode(self.channel_data, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int PpmMessage_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::channel_data::decode(self.channel_data, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature PpmMessage_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x7C3F4330C6EBEBC0ULL);

    FieldTypes::channel_data::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef PpmMessage_<0> PpmMessage;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::spear::general::PpmMessage > _uavcan_gdtr_registrator_PpmMessage;

}

} // Namespace general
} // Namespace spear

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::spear::general::PpmMessage >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::spear::general::PpmMessage::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::spear::general::PpmMessage >::stream(Stream& s, ::spear::general::PpmMessage::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "channel_data: ";
    YamlStreamer< ::spear::general::PpmMessage::FieldTypes::channel_data >::stream(s, obj.channel_data, level + 1);
}

}

namespace spear
{
namespace general
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::spear::general::PpmMessage::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::spear::general::PpmMessage >::stream(s, obj, 0);
    return s;
}

} // Namespace general
} // Namespace spear

#endif // SPEAR_GENERAL_PPMMESSAGE_HPP_INCLUDED