// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/register/384.Access.1.0.uavcan
//
// Template:
// ServiceType.j2
//
// Generated at:  2020-08-21 01:54:43.120405 UTC
// Is deprecated: no
// Fixed port ID: 384
// Full name:     uavcan.register.Access
// Version:       1.0

#ifndef UAVCAN_REGISTER_ACCESS_INCLUDED
#define UAVCAN_REGISTER_ACCESS_INCLUDED

#include <nunavut/support/nunavut.h>
#include <uavcan/_register/Name_1_0.h>
#include <uavcan/_register/Value_1_0.h>
#include <uavcan/time/SynchronizedTimestamp_1_0.h>
#include <stdbool.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
// +------------------------------------------------------------------------------------------------------------------+
// | Begin service definitions for uavcan_register_Access_1_0
// +------------------------------------------------------------------------------------------------------------------+



typedef struct
{
    uavcan_register_Name_1_0 name;
    uavcan_register_Value_1_0 value;
} uavcan_register_Access_1_0_Request;

/// Initialize an uavcan_register_Access_1_0_Request instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_register_Access_1_0_Request_init(uavcan_register_Access_1_0_Request* const out_instance)
{
    if (out_instance != NULL)
    {
        uavcan_register_Name_1_0_init(&(out_instance->name));
        uavcan_register_Value_1_0_init(&(out_instance->value));
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_register_Access_1_0_Request
/// instance.
#define uavcan_register_Access_1_0_Request_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (310U)


// +------------------------------------------------------------------------------------------------------------------+


typedef struct
{
    uavcan_time_SynchronizedTimestamp_1_0 timestamp;
    bool _mutable;
    bool persistent;
    uavcan_register_Value_1_0 value;
} uavcan_register_Access_1_0_Response;

/// Initialize an uavcan_register_Access_1_0_Response instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_register_Access_1_0_Response_init(uavcan_register_Access_1_0_Response* const out_instance)
{
    if (out_instance != NULL)
    {
        uavcan_time_SynchronizedTimestamp_1_0_init(&(out_instance->timestamp));
        out_instance->_mutable = 0;
        out_instance->persistent = 0;
        /* Ignoring 6 padding bit(s). */
        uavcan_register_Value_1_0_init(&(out_instance->value));
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_register_Access_1_0_Response
/// instance.
#define uavcan_register_Access_1_0_Response_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (267U)



/// uavcan_register_Access_1_0 can only be used with the fixed port identifier defined here.
#define uavcan_register_Access_1_0_FIXED_PORT_ID (384U)

/// Serialization of uavcan_register_Access_1_0_Request instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_register_Access_1_0_Request_serialize(const uavcan_register_Access_1_0_Request* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.register.Name.1.0
    rc = uavcan_register_Name_1_0_serialize(&(in_instance->name), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.register.Name.1.0
    // Begin Structure: uavcan.register.Value.1.0
    rc = uavcan_register_Value_1_0_serialize(&(in_instance->value), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.register.Value.1.0

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_register_Access_1_0_Request instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_register_Access_1_0_Request_deserialize(uavcan_register_Access_1_0_Request* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.register.Name.1.0
    rc = uavcan_register_Name_1_0_deserialize(&(out_instance->name), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.register.Name.1.0
    // Begin Structure: uavcan.register.Value.1.0
    rc = uavcan_register_Value_1_0_deserialize(&(out_instance->value), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.register.Value.1.0

    return offset;
}


/// Serialization of uavcan_register_Access_1_0_Response instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_register_Access_1_0_Response_serialize(const uavcan_register_Access_1_0_Response* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.time.SynchronizedTimestamp.1.0
    rc = uavcan_time_SynchronizedTimestamp_1_0_serialize(&(in_instance->timestamp), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.time.SynchronizedTimestamp.1.0
    // Begin Structure: saturated bool
    
        nunavutSetBit(out_buffer, offset, in_instance->_mutable);
        offset += 1;
    // End Structure: saturated bool
    // Begin Structure: saturated bool
    
        nunavutSetBit(out_buffer, offset, in_instance->persistent);
        offset += 1;
    // End Structure: saturated bool
    // Begin Structure: void6
    offset += 6;
    // End Structure: void6
    // Begin Structure: uavcan.register.Value.1.0
    rc = uavcan_register_Value_1_0_serialize(&(in_instance->value), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.register.Value.1.0

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_register_Access_1_0_Response instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_register_Access_1_0_Response_deserialize(uavcan_register_Access_1_0_Response* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.time.SynchronizedTimestamp.1.0
    rc = uavcan_time_SynchronizedTimestamp_1_0_deserialize(&(out_instance->timestamp), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.time.SynchronizedTimestamp.1.0
    // Begin Structure: saturated bool
    out_instance->_mutable = nunavutGetBit(in_buffer, buf_size_bytes, offset);
    offset += 1;
    // End Structure: saturated bool
    // Begin Structure: saturated bool
    out_instance->persistent = nunavutGetBit(in_buffer, buf_size_bytes, offset);
    offset += 1;
    // End Structure: saturated bool
    // Begin Structure: void6
    offset += 6;
    // End Structure: void6
    // Begin Structure: uavcan.register.Value.1.0
    rc = uavcan_register_Value_1_0_deserialize(&(out_instance->value), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.register.Value.1.0

    return offset;
}


// +------------------------------------------------------------------------------------------------------------------+
// | End service definitions for uavcan_register_Access_1_0
// +------------------------------------------------------------------------------------------------------------------+

#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_REGISTER_ACCESS */
