// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/register/385.List.1.0.uavcan
//
// Template:
// ServiceType.j2
//
// Generated at:  2020-08-21 01:54:43.354232 UTC
// Is deprecated: no
// Fixed port ID: 385
// Full name:     uavcan.register.List
// Version:       1.0

#ifndef UAVCAN_REGISTER_LIST_INCLUDED
#define UAVCAN_REGISTER_LIST_INCLUDED

#include <nunavut/support/nunavut.h>
#include <uavcan/_register/Name_1_0.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
// +------------------------------------------------------------------------------------------------------------------+
// | Begin service definitions for uavcan_register_List_1_0
// +------------------------------------------------------------------------------------------------------------------+



typedef struct
{
    uint16_t index;
} uavcan_register_List_1_0_Request;

/// Initialize an uavcan_register_List_1_0_Request instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_register_List_1_0_Request_init(uavcan_register_List_1_0_Request* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->index = 0;
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_register_List_1_0_Request
/// instance.
#define uavcan_register_List_1_0_Request_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (2U)


// +------------------------------------------------------------------------------------------------------------------+


typedef struct
{
    uavcan_register_Name_1_0 name;
} uavcan_register_List_1_0_Response;

/// Initialize an uavcan_register_List_1_0_Response instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_register_List_1_0_Response_init(uavcan_register_List_1_0_Response* const out_instance)
{
    if (out_instance != NULL)
    {
        uavcan_register_Name_1_0_init(&(out_instance->name));
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_register_List_1_0_Response
/// instance.
#define uavcan_register_List_1_0_Response_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (51U)



/// uavcan_register_List_1_0 can only be used with the fixed port identifier defined here.
#define uavcan_register_List_1_0_FIXED_PORT_ID (385U)

/// Serialization of uavcan_register_List_1_0_Request instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_register_List_1_0_Request_serialize(const uavcan_register_List_1_0_Request* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint16
    
        nunavutSetUxx(out_buffer, offset, in_instance->index, 16);
        offset += 16;
    // End Structure: saturated uint16

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_register_List_1_0_Request instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_register_List_1_0_Request_deserialize(uavcan_register_List_1_0_Request* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: saturated uint16
    out_instance->index = nunavutGetU16(in_buffer, buf_size_bytes, offset, 16);
    offset += 16;
    // End Structure: saturated uint16

    return offset;
}


/// Serialization of uavcan_register_List_1_0_Response instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_register_List_1_0_Response_serialize(const uavcan_register_List_1_0_Response* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.register.Name.1.0
    rc = uavcan_register_Name_1_0_serialize(&(in_instance->name), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.register.Name.1.0

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_register_List_1_0_Response instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_register_List_1_0_Response_deserialize(uavcan_register_List_1_0_Response* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.register.Name.1.0
    rc = uavcan_register_Name_1_0_deserialize(&(out_instance->name), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.register.Name.1.0

    return offset;
}


// +------------------------------------------------------------------------------------------------------------------+
// | End service definitions for uavcan_register_List_1_0
// +------------------------------------------------------------------------------------------------------------------+

#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_REGISTER_LIST */
