// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/node/434.GetTransportStatistics.0.1.uavcan
//
// Template:
// ServiceType.j2
//
// Generated at:  2020-08-21 01:54:40.200869 UTC
// Is deprecated: no
// Fixed port ID: 434
// Full name:     uavcan.node.GetTransportStatistics
// Version:       0.1

#ifndef UAVCAN_NODE_GET_TRANSPORT_STATISTICS_INCLUDED
#define UAVCAN_NODE_GET_TRANSPORT_STATISTICS_INCLUDED

#include <nunavut/support/nunavut.h>
#include <uavcan/node/IOStatistics_0_1.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
// +------------------------------------------------------------------------------------------------------------------+
// | Begin service definitions for uavcan_node_GetTransportStatistics_0_1
// +------------------------------------------------------------------------------------------------------------------+



typedef struct
{
    uint8_t _dummy_;
} uavcan_node_GetTransportStatistics_0_1_Request;

/// Initialize an uavcan_node_GetTransportStatistics_0_1_Request instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_node_GetTransportStatistics_0_1_Request_init(uavcan_node_GetTransportStatistics_0_1_Request* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->_dummy_ = 0U;
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_node_GetTransportStatistics_0_1_Request
/// instance.
#define uavcan_node_GetTransportStatistics_0_1_Request_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (0U)


// +------------------------------------------------------------------------------------------------------------------+

#define uavcan_node_GetTransportStatistics_0_1_Response_MAX_NETWORK_INTERFACES (3)

typedef struct
{
    uavcan_node_IOStatistics_0_1 transfer_statistics;
    size_t network_interface_statistics_length;
    uavcan_node_IOStatistics_0_1 network_interface_statistics[3];
} uavcan_node_GetTransportStatistics_0_1_Response;

/// The maximum capacity of uavcan_node_GetTransportStatistics_0_1_Response.network_interface_statistics.
static inline size_t uavcan_node_GetTransportStatistics_0_1_Response_network_interface_statistics_array_capacity(void)
{
    return (3U);
}

/// If true then uavcan_node_GetTransportStatistics_0_1_Response.network_interface_statistics's length can vary otherwise it will
/// always be the same as its capacity.
static inline bool uavcan_node_GetTransportStatistics_0_1_Response_network_interface_statistics_array_is_variable_length(void)
{
    return (true);
}

/// If uavcan_node_GetTransportStatistics_0_1_Response.network_interface_statistics is a variable length array then this is the current
/// number of items populated in the array starting from index 0. If network_interface_statistics is not a variable length array
/// then this is the same as its capacity.
static inline size_t uavcan_node_GetTransportStatistics_0_1_Response_network_interface_statistics_array_length(
    const uavcan_node_GetTransportStatistics_0_1_Response* const instance)
{
    return (instance == NULL) ? 0 : instance->network_interface_statistics_length;
}

/// Initialize an uavcan_node_GetTransportStatistics_0_1_Response instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_node_GetTransportStatistics_0_1_Response_init(uavcan_node_GetTransportStatistics_0_1_Response* const out_instance)
{
    if (out_instance != NULL)
    {
        uavcan_node_IOStatistics_0_1_init(&(out_instance->transfer_statistics));
        out_instance->network_interface_statistics_length = 0;
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_node_GetTransportStatistics_0_1_Response
/// instance.
#define uavcan_node_GetTransportStatistics_0_1_Response_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (61U)



/// uavcan_node_GetTransportStatistics_0_1 can only be used with the fixed port identifier defined here.
#define uavcan_node_GetTransportStatistics_0_1_FIXED_PORT_ID (434U)

/// Serialization of uavcan_node_GetTransportStatistics_0_1_Request instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_node_GetTransportStatistics_0_1_Request_serialize(const uavcan_node_GetTransportStatistics_0_1_Request* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_node_GetTransportStatistics_0_1_Request instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_node_GetTransportStatistics_0_1_Request_deserialize(uavcan_node_GetTransportStatistics_0_1_Request* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    

    return offset;
}


/// Serialization of uavcan_node_GetTransportStatistics_0_1_Response instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_node_GetTransportStatistics_0_1_Response_serialize(const uavcan_node_GetTransportStatistics_0_1_Response* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.node.IOStatistics.0.1
    rc = uavcan_node_IOStatistics_0_1_serialize(&(in_instance->transfer_statistics), offset, out_buffer);
        if (rc < 0)
        {
            return rc;
        }
        offset = rc;
    // End Structure: uavcan.node.IOStatistics.0.1
    // Begin Structure: uavcan.node.IOStatistics.0.1[<=3]
    
        if (in_instance->network_interface_statistics_length > 3)
        {
            return -NUNAVUT_ERR_INVALID_LEN;
        }
        nunavutSetUxx(out_buffer, offset, in_instance->network_interface_statistics_length, 8);
        offset += 8;
    // End Structure: uavcan.node.IOStatistics.0.1[<=3]

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_node_GetTransportStatistics_0_1_Response instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_node_GetTransportStatistics_0_1_Response_deserialize(uavcan_node_GetTransportStatistics_0_1_Response* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: uavcan.node.IOStatistics.0.1
    rc = uavcan_node_IOStatistics_0_1_deserialize(&(out_instance->transfer_statistics), offset, in_buffer, buf_size_bytes);
    if (rc < 0)
    {
        return rc;
    }
    offset = rc;
    // End Structure: uavcan.node.IOStatistics.0.1
    // Begin Structure: uavcan.node.IOStatistics.0.1[<=3]
    
    out_instance->network_interface_statistics_length = nunavutGetU8(in_buffer, buf_size_bytes, offset, 8);;
    offset += 8;
    if (out_instance->network_interface_statistics_length > 3)
    {
        return -NUNAVUT_ERR_INVALID_LEN;
    }
    // End Structure: uavcan.node.IOStatistics.0.1[<=3]

    return offset;
}


// +------------------------------------------------------------------------------------------------------------------+
// | End service definitions for uavcan_node_GetTransportStatistics_0_1
// +------------------------------------------------------------------------------------------------------------------+

#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_NODE_GET_TRANSPORT_STATISTICS */
