// UAVCAN data structure definition.                                                                          +-+ +-+
//                                                                                                            | | | |
// AUTOGENERATED, DO NOT EDIT.                                                                                \  -  /
//                                                                                                              ---
//                                                                                                               o
// +------------------------------------------------------------------------------------------------------------------+
//
// Generator:
// nunavut-0.3.4 (serialization was enabled)
//
//
// Source File:
// /home/david/Documents/Clubs/SPEAR/uavcan_dsdl/public_regulated_data_types/uavcan/node/IOStatistics.0.1.uavcan
//
// Template:
// StructureType.j2
//
// Generated at:  2020-08-21 01:54:40.480680 UTC
// Is deprecated: no
// Fixed port ID: None
// Full name:     uavcan.node.IOStatistics
// Version:       0.1

#ifndef UAVCAN_NODE_IOSTATISTICS_INCLUDED
#define UAVCAN_NODE_IOSTATISTICS_INCLUDED

#include <nunavut/support/nunavut.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


typedef struct
{
    uint64_t num_emitted;
    uint64_t num_received;
    uint64_t num_errored;
} uavcan_node_IOStatistics_0_1;

/// Initialize an uavcan_node_IOStatistics_0_1 instance to default values.
/// No memory is allocated within this method.
/// Does nothing if @ref out_instance is NULL.
///
/// @param out_instance A structure instance to Initialize.
static inline void uavcan_node_IOStatistics_0_1_init(uavcan_node_IOStatistics_0_1* const out_instance)
{
    if (out_instance != NULL)
    {
        out_instance->num_emitted = 0;
        out_instance->num_received = 0;
        out_instance->num_errored = 0;
    }
}

/// Contains the maximum number of bytes needed to serialize a(n) uavcan_node_IOStatistics_0_1
/// instance.
#define uavcan_node_IOStatistics_0_1_MAX_SERIALIZED_REPRESENTATION_SIZE_BYTES \
        (15U)


/// Serialization of uavcan_node_IOStatistics_0_1 instance into a byte array.
///
/// @param in_instance   A structure instance to serialize.
/// @param offset        Offset (in bits) of data type in message.
/// @param out_buffer    Output message buffer.
///
/// @returns             Size of encoded data (in bits)
static inline NunavutSignedBitLength uavcan_node_IOStatistics_0_1_serialize(const uavcan_node_IOStatistics_0_1* in_instance, NunavutUnsignedBitLength offset, uint8_t* const out_buffer)
{
    NunavutSignedBitLength rc = 0;

    if (out_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: truncated uint40
    
        nunavutSetUxx(out_buffer, offset, in_instance->num_emitted, 40);
        offset += 40;
    // End Structure: truncated uint40
    // Begin Structure: truncated uint40
    
        nunavutSetUxx(out_buffer, offset, in_instance->num_received, 40);
        offset += 40;
    // End Structure: truncated uint40
    // Begin Structure: truncated uint40
    
        nunavutSetUxx(out_buffer, offset, in_instance->num_errored, 40);
        offset += 40;
    // End Structure: truncated uint40

    return offset;
}

/// Deserialization of byte-array encoding into uavcan_node_IOStatistics_0_1 instance.
///
/// @param out_instance      Structure instance to write data to.
/// @param offset            Bit offset of structure in data buffer.
/// @param in_buffer         Message buffer to deserialize.
/// @param buf_size_bytes    Length of input buffer (in bytes) to avoid overflow.
///
/// @returns                 Size of decoded data (in bits)
static inline NunavutSignedBitLength uavcan_node_IOStatistics_0_1_deserialize(uavcan_node_IOStatistics_0_1* const out_instance, NunavutUnsignedBitLength offset, uint8_t* const in_buffer, const size_t buf_size_bytes)
{
    NunavutSignedBitLength rc = 0;

    if (in_buffer == NULL)
    {
        return -NUNAVUT_ERR_INVALID_BUF;
    }
    
    // Begin Structure: truncated uint40
    out_instance->num_emitted = nunavutGetU64(in_buffer, buf_size_bytes, offset, 40);
    offset += 40;
    // End Structure: truncated uint40
    // Begin Structure: truncated uint40
    out_instance->num_received = nunavutGetU64(in_buffer, buf_size_bytes, offset, 40);
    offset += 40;
    // End Structure: truncated uint40
    // Begin Structure: truncated uint40
    out_instance->num_errored = nunavutGetU64(in_buffer, buf_size_bytes, offset, 40);
    offset += 40;
    // End Structure: truncated uint40

    return offset;
}


#ifdef __cplusplus
} /* End extern "C" */
#endif /* __cplusplus */
#endif /* UAVCAN_NODE_IOSTATISTICS */
